"""initial

Revision ID: d10311bdf0be
Revises:
Create Date: 2026-09-29 22:38:20.806755
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d10311bdf0be"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("avatar_key", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("actor_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_table(
        "lists",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("cover_key", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_by", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "login_sessions",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_login_sessions_user_id"), "login_sessions", ["user_id"], unique=False)
    op.create_table(
        "pending_uploads",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("thumbnail_key", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pending_uploads_user_id"), "pending_uploads", ["user_id"], unique=False
    )
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("list_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("reviewed_by", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["lists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_import_batches_list_id"), "import_batches", ["list_id"], unique=False)
    op.create_table(
        "items",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("list_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("dedupe_key", sa.String(length=512), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("cover_key", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("suggested_action", sa.Text(), nullable=True),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("reference_note", sa.Text(), nullable=True),
        sa.Column("reference_as_of", sa.DateTime(timezone=True), nullable=True),
        sa.Column("missing_fields", sa.JSON(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("place_kind", sa.String(length=24), nullable=False),
        sa.Column("place_name", sa.String(length=160), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("area", sa.String(length=160), nullable=True),
        sa.Column("online_url", sa.String(length=2048), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("coordinate_system", sa.String(length=24), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90 OR latitude IS NULL", name="item_latitude"),
        sa.CheckConstraint(
            "longitude BETWEEN -180 AND 180 OR longitude IS NULL", name="item_longitude"
        ),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["lists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("list_id", "dedupe_key", name="uq_item_within_list"),
    )
    op.create_index(op.f("ix_items_list_id"), "items", ["list_id"], unique=False)
    op.create_index("ix_items_list_sort", "items", ["list_id", "sort_order"], unique=False)
    op.create_table(
        "checkins",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("item_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("idempotency_key", sa.String(length=80), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("share_id", sa.String(length=64), nullable=False),
        sa.Column("experienced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("visibility", sa.String(length=24), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("accuracy_m", sa.Float(), nullable=True),
        sa.Column("coordinate_system", sa.String(length=24), nullable=True),
        sa.Column("located_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hidden_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "latitude BETWEEN -90 AND 90 OR latitude IS NULL", name="checkin_latitude"
        ),
        sa.CheckConstraint(
            "longitude BETWEEN -180 AND 180 OR longitude IS NULL", name="checkin_longitude"
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("share_id"),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_checkin_idempotency"),
    )
    op.create_index(op.f("ix_checkins_item_id"), "checkins", ["item_id"], unique=False)
    op.create_index(
        "ix_checkins_item_public",
        "checkins",
        ["item_id", "visibility", "deleted_at", "hidden_at"],
        unique=False,
    )
    op.create_index(op.f("ix_checkins_user_id"), "checkins", ["user_id"], unique=False)
    op.create_table(
        "item_links",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("item_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_links_item_id"), "item_links", ["item_id"], unique=False)
    op.create_table(
        "item_relations",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("item_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("related_item_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("relation_kind", sa.String(length=24), nullable=False),
        sa.CheckConstraint("item_id != related_item_id", name="no_self_relation"),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["related_item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id", "related_item_id", name="uq_item_relation"),
    )
    op.create_table(
        "media",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("checkin_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("thumbnail_key", sa.String(length=255), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["checkin_id"],
            ["checkins.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_media_checkin_id"), "media", ["checkin_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_checkin_id"), table_name="media")
    op.drop_table("media")
    op.drop_table("item_relations")
    op.drop_index(op.f("ix_item_links_item_id"), table_name="item_links")
    op.drop_table("item_links")
    op.drop_index(op.f("ix_checkins_user_id"), table_name="checkins")
    op.drop_index("ix_checkins_item_public", table_name="checkins")
    op.drop_index(op.f("ix_checkins_item_id"), table_name="checkins")
    op.drop_table("checkins")
    op.drop_index("ix_items_list_sort", table_name="items")
    op.drop_index(op.f("ix_items_list_id"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_import_batches_list_id"), table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index(op.f("ix_pending_uploads_user_id"), table_name="pending_uploads")
    op.drop_table("pending_uploads")
    op.drop_index(op.f("ix_login_sessions_user_id"), table_name="login_sessions")
    op.drop_table("login_sessions")
    op.drop_table("lists")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("users")
    # ### end Alembic commands ###
